### ISSUE TITLE
Tp into water

### ISSUE THREAD

**Issue by adelando** [Varjokudos/WildTP#1]
Hello,

Thanks for a quick and easy to use plugin!

I have however noticed that whenever i Tp with a sign i always land in water (1 block deep water) or get pushed from a dirt block into the water because i tp into the block instead ontop of it.

**Comment by Varjokudos** [comment]
Hi there,

just small question so I know where to start looking to fix this issue. Are you using the latest version which is `1.1.1`?

**Comment by adelando** [comment]
I am using plugin version 1.1.1 and on 1.15.2 if that helps

**Comment by Varjokudos** [comment]
I have uploaded new version of the plugin that should fix your problem. Please open up new issue if this problem occurs again. Just keep in mind that if your set teleportation border to false and your server is running slow it can occasionnally teleport you to random _wrong_ places. This is because it has not fully rendered the area.

You can find the new bugfix version here 
https://www.spigotmc.org/resources/wildtp-safe-teleportation.75500/update?update=320207

Please leave a review on my resource page, this would be much appreciated.

**Comment by adelando** [comment]
i believe im still having the same issue, but this time it now lags the server

https://pastebin.com/pezyJWe2

**Comment by Varjokudos** [comment]
Oh, interesting. Have you set radius for the teleport or have you allowed to plugin to use any coordinates? Also how much RAM does your server have? Do you have many other plugins on your server?

While I wait your answer I will try to find solution to reduce the lag from the plugin :)

**Comment by adelando** [comment]
i have the radius set to 2000 as default in the config, i also have 5gb of ram.. here is my start up log aswell to see the full list of plugins i have...

[latest.log](https://github.com/Varjokudos/WildTP/files/4275497/latest.log)

**Comment by Varjokudos** [comment]
Could you send me the timings of your server?

**Comment by Varjokudos** [comment]
I have implemented cooldowns to signs and commands now so your players can't now spam the command which would cause more lag to your server. Please update the plugin and see if that eases the lag.

Just remember there may be other plugins on your server that require a lot of RAM that will cause lag to server.

Newest update can be found here: https://www.spigotmc.org/resources/wildtp-safe-teleportation.75500/update?update=320673
