### ISSUE TITLE
Some reason, WildTP lags server then crashes it when you do /rtp

### ISSUE THREAD

**Issue by IITFA** [Varjokudos/WildTP#2]
This didn't happen when I first installed the plugin, but today it has. The logs are so full of thread dump stuff I'm not even sure what to look for or paste, but the lag is triggered when I do /rtp

The only recent change has been updating paper spigot to paper-126.jar but that may be related. Sorry that I can't be more helpful here.

**Comment by Varjokudos** [comment]
Hmm, weird. I have not run many tests on paper servers with this plugin because by the default this plugin should work on both spigot and paper. I will do some testing with the plugin on that paper-126.jar to see if I find any solution for it.

Meanwhile could I get some information about your server? How much you have RAM on it and how much you have disk space? Do you have many plugins on your servers? Maybe post timings of your servers here too :) Thank you in advance!

**Comment by Varjokudos** [comment]
Will get back to this once more information is provided.
